### ISSUE TITLE
How are cell segmented across tiles and z-planes?

### ISSUE THREAD

**Issue by pakiessling** [Vizgen/vizgen-postprocessing#11]
Hi I am currently training cellpose on our own Merscope data for use with your postprocessing tool.
I am wondering **whether I should train the model to only segment cells with nuclei or not**.

I am unsure how this would affect the segmentation of cells across z-planes.

Could you describe how the tool identifies and merges cell entities across tiles and z-planes and wether the existence of DAPI signal in the cell plays a role in that?

**Comment by timwiggin** [comment]
Short answer: VPT does not require that the cells have nuclei, and image intensity data is not used to stitch cells across z-planes or tiles.

**Stitching across tiles**
The methods available for combining/splitting cells between tiles is the same as the methods for combining cells between segmentation methods. The options are described in more detail here: https://vizgen.github.io/vizgen-postprocessing/segmentation_options/task_fusion_definition.html

**Stitching across z-planes**
Stitching across z is somewhat complicated and depends on the number of z-planes that are selected for segmentation. Generally, cells that have overlapping area >50% with cells in an adjacent z-slice are merged. If segmentation is selected on alternating z planes (e.g. plane 1, 3, 5), empty z-planes are filled in by the closest segmented plane.

Function for filling in z-planes:
https://github.com/Vizgen/vizgen-postprocessing/blob/64e501620c771980cce5d1fb34415e7796665c98/src/vpt/segmentation/utils/seg_result.py#L96

Function for combining cells across z-planes:
https://github.com/Vizgen/vizgen-postprocessing/blob/64e501620c771980cce5d1fb34415e7796665c98/src/vpt/segmentation/utils/seg_result.py#L107

**Comment by pakiessling** [comment]
Thanks @timwiggin
