### ISSUE TITLE
Using the tool with non-cellpose/watershed segmentation algorithm

### ISSUE THREAD

**Issue by pakiessling** [Vizgen/vizgen-postprocessing#12]
Hi @timwiggin ,

I am evaluating different segmentation algorithms and so far it looks like the best performance for my tissue comes from a different tool.

Is it possible to plug in a mask per tile and then continue from `compile-tile-segmentation` and how would I go about doing that?

Thank you!

**Comment by timwiggin** [comment]
Thanks for reaching out! Unfortunately, VPT doesn't accept segmentation masks as an input. 

If you're able to convert the masks into cell boundary polygons, it may be possible to import the cell boundaries into parquet format using the `convert-geometry` tool:
https://vizgen.github.io/vizgen-postprocessing/command_line_interface/index.html#required-arguments

`convert-geometry` currently supports QuPath-formatted geojson files and Vizgen-formatted hdf5 cell boundary inputs.

**Comment by pakiessling** [comment]
Ok, I will give it a shot :)
