### ISSUE TITLE
Run-segmentation ​stops after run-segmentation-on-tile​

### ISSUE THREAD

**Issue by pakiessling** [Vizgen/vizgen-postprocessing#13]
Hi, I tried out the tool on a `mosaic_DAPI_z3.tif` file in watershed nucleus mode:

`vpt --processes 20 --verbose run-segmentation --segmentation-algorithm ./segmentation.json --input-images "mosaic_(?P<stain>.*?)_z(?P<z>[0-9]+).tif" --output-path out/ --input-micron-to-mosaic ./micron_to_mosaic_pixel_transform.csv`

At the end I receive a .parquet for every tile, but not a combined .parquet. Nothing interesting in the log files, just a lot of Dask memory leak warnings.
What went wrong and how can I check if the segmentation was completed?

Thank you!

**Comment by lguerard** [comment]
Hi sorry to revive this.

But I'm also having issues with multiple processes and the `run-segmentation`, it seems that it does everything for the tiles, but never starts the combining step. Everything works fine with only 1 process though.

Did you figure out the issues or a fix in the end ?

**Comment by poloarol** [comment]
Hello @pakiessling,

Please would it be possible to share with us what you did to move forward?

Thanks

**Comment by pakiessling** [comment]
@lguerard @poloarol 

I do not remember what the problem was back then.

This is the script I am using succefully for multiple different vpt versions:

https://gist.github.com/pakiessling/f046eb48a43e77ad634371142be09542

**Comment by poloarol** [comment]
@pakiessling thanks for the tip
