### ISSUE TITLE
unable to run on test dataset

### ISSUE THREAD

**Issue by ucagenomix** [Vizgen/vizgen-postprocessing#4]
Hello,

Could you please provide some command lines to run vpt on the test data set ?

```
$> git clone https://github.com/Vizgen/vizgen-postprocessing.git
$> cd vizgen-postprocessing/tests/data
$> vpt run-segmentation 
--segmentation-algorithm segmentation_algorithm.json 
--input-micron-to-mosaic micron_to_mosaic_pixel_transform.csv 
--output-path output 
--input-images input_images/?P<z>[0-9]
```

i don't clearly understand the regexp for the --input-images parameter, could be more explicit how to use it ?

```
$> vpt run-segmentation 
--segmentation-algorithm cellpose_1.json 
--input-micron-to-mosaic micron_to_mosaic_pixel_transform.csv 
--output-path results 
--input-images input_images/'mosaic_(?P<stain>[\w|-]+[0-9]?)_z(?P<z>[0-9]+).tif'

```
this seems to work

**Comment by timwiggin** [comment]
Using a regular expression for `--input-images` allows a lot of flexibility but there can be a bit of a learning curve. We're working on making this feature more user friendly.

Here's a template you could try editing to match your data organization:
`--input-images="/path/to/data/experiment_name/region_0/images/mosaic_(?P<stain>[\w|-]+[0-9]?)_z(?P<z>[0-9]+).tif"`

Some things to note:
* Enclosing the entire argument in quotes prevents the shell from parsing the `\` character in the regex
* The path given can be either relative to the working directory or absolute
* Forward slashes are recommended in the regular expression even when running on Windows

Let me know if that helps!
